name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: 3.8
    
    - name: Install dependencies
      run: |
        cd starter
        pip install -r requirements.txt
    
    - name: Install flake8
      run: pip install flake8
    
    - name: Run flake8
      run: |
        cd starter
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=79 --statistics
    
    - name: Run tests
      run: |
        cd starter
        pytest starter/test_ml_functions.py -v
